class Lists {
  List<String> languages = [
    "Select Language",
    "Afar-aa",
    "Abkhazian-ab",
    "Afrikaans-af",
    "Akan-ak",
    "Albanian-sq",
    "Amharic-am",
    "Arabic-ar",
    "Aragonese-an",
    "Armenian-hy",
    "Assamese-as",
    "Avaric-av",
    "Avestan-ae",
    "Aymara-ay",
    "Azerbaijani-az",
    "Bashkir-ba",
    "Bambara-bm",
    "Basque-eu",
    "Belarusian-be",
    "Bengali-bn",
    "Bihari languages-bh",
    "Bislama-bi",
    "Bosnian-bs",
    "Breton-br",
    "Bulgarian-bg",
    "Burmese-my",
    "Catalan; Valencian-ca",
    "Chamorro-ch",
    "Chechen-ce",
    "Chinese-zh",
    "Chuvash-cv",
    "Cornish-kw",
    "Corsican-co",
    "Cree-cr",
    "Czech-cs",
    "Danish-da",
    "Divehi; Dhivehi; Maldivian-dv",
    "Dutch; Flemish-nl",
    "Dzongkha-dz",
    "English-en",
    "Esperanto-eo",
    "Estonian-et",
    "Ewe-ee",
    "Faroese-fo",
    "Fijian-fj",
    "Finnish-fi",
    "French-fr",
    "Western Frisian-fy",
    "Fulah-ff",
    "Georgian-ka",
    "German-de",
    "Gaelic; Scottish Gaelic-gd",
    "Irish-ga",
    "Galician-gl",
    "Manx-gv",
    "Greek-el",
    "Guarani-gn",
    "Gujarati-gu",
    "Haitian; Haitian Creole-ht",
    "Hausa-ha",
    "Hebrew-he",
    "Herero-hz",
    "Hindi-hi",
    "Hiri Motu-ho",
    "Croatian-hr",
    "Hungarian-hu",
    "Igbo-ig",
    "Icelandic-is",
    "Ido-io",
    "Sichuan Yi; Nuosu-ii",
    "Inuktitut-iu",
    "Indonesian-id",
    "Inupiaq-ik",
    "Italian-it",
    "Javanese-jv",
    "Japanese-ja",
    "Kalaallisut; Greenlandic-kl",
    "Kannada-kn",
    "Kashmiri-ks",
    "Kanuri-kr",
    "Kazakh-kk",
    "Central Khmer-km",
    "Kikuyu; Gikuyu-ki",
    "Kinyarwanda-rw",
    "Kirghiz; Kyrgyz-ky",
    "Komi-kv",
    "Kongo-kg",
    "Korean-ko",
    "Kuanyama; Kwanyama-kj",
    "Kurdish-ku",
    "Lao-lo",
    "Latin-la",
    "Latvian-lv",
    "Limburgan; Limburger; Limburgish-li",
    "Lingala-ln",
    "Lithuanian-lt",
    "Luxembourgish; Letzeburgesch-lb",
    "Luba-lu",
    "Ganda-lg",
    "Macedonian-mk",
    "Marshallese-mh",
    "Malayalam-ml",
    "Maori-mi",
    "Marathi-mr",
    "Malay-ms",
    "Malagasy-mg",
    "Maltese-mt",
    "Mongolian-mn",
    "Nauru-na",
    "Navajo; Navaho-nv",
    "Ndebele-nr",
    "Ndebele-nd",
    "Ndonga-ng",
    "Nepali-ne",
    "Bokmål-nb",
    "Norwegian-no",
    "Chichewa; Chewa; Nyanja-ny",
    "Occitan; Provençal-oc",
    "Ojibwa-oj",
    "Oriya-or",
    "Oromo-om",
    "Ossetian; Ossetic-os",
    "Panjabi; Punjabi-pa",
    "Persian-fa",
    "Pali-pi",
    "Polish-pl",
    "Portuguese-pt",
    "Pushto; Pashto-ps",
    "Quechua-qu",
    "Romansh-rm",
    "Romanian; Moldavian; Moldovan-ro",
    "Rundi-rn",
    "Russian-ru",
    "Sango-sg",
    "Sanskrit-sa",
    "Sinhala; Sinhalese-si",
    "Slovak-sk",
    "Slovenian-sl",
    "Northern Sami-se",
    "Samoan-sm",
    "Shona-sn",
    "Sindhi-sd",
    "Somali-so",
    "Sotho-st",
    "Spanish; Castilian-es",
    "Sardinian-sc",
    "Serbian-sr",
    "Swati-ss",
    "Sundanese-su",
    "Swahili-sw",
    "Swedish-sv",
    "Tahitian-ty",
    "Tamil-ta",
    "Tatar-tt",
    "Telugu-te",
    "Tajik-tg",
    "Tagalog-tl",
    "Thai-th",
    "Tibetan-bo",
    "Tigrinya-ti",
    "Tonga (Tonga Islands)-to",
    "Tswana-tn",
    "Tsonga-ts",
    "Turkmen-tk",
    "Turkish-tr",
    "Twi-tw",
    "Uighur; Uyghur-ug",
    "Ukrainian-uk",
    "Urdu-ur",
    "Uzbek-uz",
    "Venda-ve",
    "Vietnamese-vi",
    "Volapük-vo",
    "Welsh-cy",
    "Walloon-wa",
    "Wolof-wo",
    "Xhosa-xh",
    "Yiddish-yi",
    "Yoruba-yo",
    "Zhuang; Chuang-za",
    "Zulu-zu",
  ];
  String languagesGetter(int index) {
    return languages[index];
  }

  List<String> musicGenres = [
    "Select Music Genre",
    "Pop",
    "Hip Hop",
    "Rock",
    "Metal",
    "Kpop",
    "R&B",
    "Soul",
    "Reggae",
    "Country",
    "Funk",
    "Folk",
    "Middle Eastern",
    "Instrumental",
    "Jazz",
    "Classical",
    "Electronic",
    "Latin America",
    "Blues",
    "Africa",
    "Asia",
    "Traditional music",
    "Independent music",
  ];
  String musicGenresGetter(int index) {
    return musicGenres[index];
  }
}
enum Wifi{
  connected,
  notConnected,
  ready
}